apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: example
build:
  local:
    useBuildkit: true
  artifacts:
  - image: example-service
    docker:
      dockerfile: Dockerfile
      secret: 
        id: npmrc
        src: /Users/maxpas/.npmrc
deploy:
  kubectl:
    manifests:
    - ./k8s/deployment.yml
