apiVersion: v1
kind: Service
metadata:
  name: example-app-svc
  labels:
    app: example-app
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: example-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  labels:
    app: example-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example-service
        image: example-service
        ports:
        - containerPort: 3000